package SeleniumTest;

// Generated by Selenium IDE
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import java.util.*;
import org.junit.jupiter.api.Test;

/**
 * Selenium test to simulate the failure case while creating a new slider.
 * This test attempts to input an invalid value ('10e') in the 'y' field and
 * verifies that the application throws the appropriate error message.
 * 
 * Test Steps:
 * 1. Open the application.
 * 2. Navigate to the "Create New Slider" page.
 * 3. Fill in the slider details including an invalid value '10e' for the 'y' field.
 * 4. Attempt to save the slider.
 * 5. Verify that the correct error message is displayed.
 * 
 * Expected result: The application should display a validation error for the 'y' field.
 * 
 * Dependencies:
 * Ensure the Selenium WebDriver is correctly set up, and the application is running locally.
 * 
 * @author Guntas
 */
public class CreateSliderFailSelenium {
    private WebDriver driver;

    /**
     * Sets up the Selenium WebDriver before each test.
     * This method initializes the ChromeDriver and prepares the test environment.
     */
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        new HashMap<String, Object>(); // Initializes a HashMap (currently unused).
    }

    /**
     * Tears down the Selenium WebDriver after each test.
     * This method closes the browser and quits the driver instance.
     */
    @After
    public void tearDown() {
        driver.quit();
    }

    /**
     * Test case for creating a slider with invalid input in the 'y' field.
     * 
     * Steps:
     * 1. Open the application homepage.
     * 2. Navigate to the "Show All Slider Items" page.
     * 3. Navigate to the "Create New Slider" page.
     * 4. Fill in valid values for 'size', 'x', and 'maxTravel' fields.
     * 5. Provide an invalid value '10e' for the 'y' field.
     * 6. Attempt to save the slider.
     * 7. Verify that the correct validation error message is shown for the 'y' field.
     */
    @Test
    public void createsliderfail() {
        // Step 1: Open the application homepage
        driver.get("http://localhost:8080/Slider/");
        
        // Step 2: Set browser window size
        driver.manage().window().setSize(new Dimension(945, 1060));
        
        // Step 3: Navigate to "Show All Slider Items" page
        driver.findElement(By.linkText("Show All Slider Items")).click();
        
        // Step 4: Navigate to "Create New Slider" page
        driver.findElement(By.linkText("Create New Slider")).click();
        
        // Step 5: Click on the first row (not required for the test but simulates user actions)
        driver.findElement(By.cssSelector("tr:nth-child(1)")).click();
        
        // Step 6: Fill in valid slider fields
        driver.findElement(By.id("j_idt12:size")).sendKeys("10");  // 'size'
        driver.findElement(By.id("j_idt12:x")).click(); // Click on 'x' field
        driver.findElement(By.id("j_idt12:x")).sendKeys("10");  // 'x'
        driver.findElement(By.id("j_idt12:y")).click(); // Click on 'y' field
        
        // Step 7: Enter invalid value '10e' in the 'y' field
        driver.findElement(By.id("j_idt12:y")).sendKeys("10e");
        
        // Step 8: Fill in other fields
        driver.findElement(By.id("j_idt12:maxTravel")).click(); // Click on 'maxTravel' field
        driver.findElement(By.id("j_idt12:maxTravel")).sendKeys("10"); // 'maxTravel'
        
        // Step 9: Click on 'currentTravel' field and enter value
        driver.findElement(By.id("j_idt12:currentTravel")).click();
        WebElement element = driver.findElement(By.id("j_idt12:currentTravel"));
        Actions builder = new Actions(driver);
        builder.doubleClick(element).perform();
        driver.findElement(By.id("j_idt12:currentTravel")).sendKeys("10");  // 'currentTravel'
        
        // Step 10: Attempt to save the slider
        driver.findElement(By.linkText("Save")).click();
        
        // Step 11: Click anywhere on the page (simulates user interaction)
        driver.findElement(By.cssSelector("html")).click();
        
        // Step 12: Verify that the correct error message is displayed for the 'y' field
        // The error message should indicate that '10e' is not a valid number
        assertThat(driver.findElement(By.cssSelector("table:nth-child(1) td")).getText(),
                is("j_idt12:y: '10e' must be a number consisting of one or more digits."));
    }
}
