package SeleniumTest;

// Generated by Selenium IDE

import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import org.junit.jupiter.api.Test;

/**
 * Selenium test for simulating login failure scenarios.
 * This test enters incorrect login credentials multiple times and verifies 
 * that the login fails until the correct credentials are provided.
 * 
 * Test Steps:
 * 1. Open the login page.
 * 2. Try logging in with incorrect credentials.
 * 3. Attempt logging in with another set of incorrect credentials.
 * 4. Finally, try logging in with valid credentials.
 * 5. Verify that after a successful login, the "Create New Slider" link appears.
 * 
 * Expected result: The test should pass if the "Create New Slider" link appears only after correct credentials are provided.
 * 
 * Dependencies:
 * Ensure that the Selenium WebDriver is properly set up and the application is running locally.
 * 
 * @author Guntas
 */
public class LoginFailSelenium {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  /**
   * Sets up the Selenium WebDriver before each test.
   * Initializes the ChromeDriver, JavascriptExecutor, and necessary variables.
   */
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  /**
   * Tears down the Selenium WebDriver after each test.
   * Closes the browser and quits the WebDriver session.
   */
  @After
  public void tearDown() {
    driver.quit();
  }

  /**
   * Test case for login failure.
   * 
   * Steps:
   * 1. Open the login page.
   * 2. Try to log in with incorrect credentials ("1234" as username and password).
   * 3. Attempt login with another set of incorrect credentials ("Guntas_admin" and "1234567890").
   * 4. Try login with valid credentials ("Guntas_admin" and "1234").
   * 5. Verify that the "Create New Slider" link appears only after valid login.
   */
  @Test
  public void loginFail() {
    // Step 1: Open the login page
    driver.get("http://localhost:8080/Slider/faces/slider/List.xhtml");

    // Step 2: Set the browser window size
    driver.manage().window().setSize(new Dimension(1294, 1080));

    // Step 3: Click on the username field and type an invalid username
    driver.findElement(By.id("j_username")).click();
    driver.findElement(By.id("j_username")).sendKeys("1234");

    // Step 4: Click on the password field and type an invalid password
    driver.findElement(By.id("j_password")).click();
    driver.findElement(By.id("j_password")).sendKeys("1234");

    // Step 5: Click the login button
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();

    // Step 6: Click on the username field again and type another incorrect username
    driver.findElement(By.id("j_username")).click();
    driver.findElement(By.id("j_username")).sendKeys("Guntas_admin");

    // Step 7: Click on the password field and type another incorrect password
    driver.findElement(By.id("j_password")).click();
    driver.findElement(By.id("j_password")).sendKeys("1234567890");

    // Step 8: Click the login button
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();

    // Step 9: Click on the username field again and type a partially incorrect username
    driver.findElement(By.id("j_username")).click();
    driver.findElement(By.id("j_username")).sendKeys("Guntas_");

    // Step 10: Click on the password field and type the correct password
    driver.findElement(By.id("j_password")).click();
    driver.findElement(By.id("j_password")).sendKeys("1234");

    // Step 11: Click the login button
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();

    // Step 12: Click on the username field and type the correct username
    driver.findElement(By.id("j_username")).click();
    driver.findElement(By.id("j_username")).sendKeys("Guntas_admin");

    // Step 13: Click on the password field and type the correct password
    driver.findElement(By.id("j_password")).click();
    driver.findElement(By.id("j_password")).sendKeys("1234");

    // Step 14: Click the login button
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();

    // Step 15: Verify that the "Create New Slider" link is present, indicating a successful login
    assertThat(driver.findElement(By.linkText("Create New Slider")).getText(), is("Create New Slider"));
  }
}
