package SeleniumTest;

// Generated by Selenium IDE

import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import org.junit.jupiter.api.Test;

/**
 * Selenium test for simulating a successful login scenario.
 * This test enters the correct login credentials and verifies 
 * that the login is successful by checking if a specific element is present after login.
 * 
 * Test Steps:
 * 1. Open the login page.
 * 2. Enter valid username and password.
 * 3. Click the login button.
 * 4. Verify that the "Create New Slider" link appears, indicating successful login.
 * 
 * Expected result: The test should pass if the "Create New Slider" link is visible after login.
 * 
 * Dependencies:
 * Ensure that the Selenium WebDriver is properly set up and the application is running locally.
 * 
 * @author Guntas
 */
public class LoginSuccessSelenium {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  /**
   * Sets up the Selenium WebDriver before each test.
   * Initializes the ChromeDriver, JavascriptExecutor, and necessary variables.
   */
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  /**
   * Tears down the Selenium WebDriver after each test.
   * Closes the browser and quits the WebDriver session.
   */
  @After
  public void tearDown() {
    driver.quit();
  }

  /**
   * Test case for login success.
   * 
   * Steps:
   * 1. Open the login page.
   * 2. Enter the valid username ("Guntas_admin").
   * 3. Enter the valid password ("1234").
   * 4. Click the login button.
   * 5. Verify that the "Create New Slider" link appears, indicating successful login.
   */
  @Test
  public void loginsuccess() {
    // Step 1: Open the login page
    driver.get("http://localhost:8080/Slider/faces/slider/List.xhtml");

    // Step 2: Set the browser window size
    driver.manage().window().setSize(new Dimension(1294, 1080));

    // Step 3: Click on the username field and type the valid username
    driver.findElement(By.id("j_username")).click();
    driver.findElement(By.id("j_username")).sendKeys("Guntas_admin");

    // Step 4: Click on the password field and type the valid password
    driver.findElement(By.id("j_password")).sendKeys("1234");

    // Step 5: Click the login button
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();

    // Step 6: Verify that the "Create New Slider" link is present, indicating a successful login
    assertThat(driver.findElement(By.linkText("Create New Slider")).getText(), is("Create New Slider"));
  }
}
