// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class CreateAppUserPassSelenium {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void createappuser() {
    // Test name: Create appuser
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/Slider/ | 
    driver.get("http://localhost:8080/Slider/");
    // 2 | setWindowSize | 945x1060 | 
    driver.manage().window().setSize(new Dimension(945, 1060));
    // 3 | click | linkText=Show All AppUser Items | 
    driver.findElement(By.linkText("Show All AppUser Items")).click();
    // 4 | click | linkText=Create New AppUser | 
    driver.findElement(By.linkText("Create New AppUser")).click();
    // 5 | click | id=j_idt12:userid | 
    driver.findElement(By.id("j_idt12:userid")).click();
    // 6 | type | id=j_idt12:userid | ayan
    driver.findElement(By.id("j_idt12:userid")).sendKeys("ayan");
    // 7 | type | id=j_idt12:password | 1234
    driver.findElement(By.id("j_idt12:password")).sendKeys("1234");
    // 8 | type | id=j_idt12:groupname | Admin
    driver.findElement(By.id("j_idt12:groupname")).sendKeys("Admin");
    // 9 | click | linkText=Save | 
    driver.findElement(By.linkText("Save")).click();
    // 10 | click | linkText=Show All AppUser Items | 
    driver.findElement(By.linkText("Show All AppUser Items")).click();
    // 11 | assertText | css=.jsfcrud_odd_row:nth-child(7) > td:nth-child(2) | ayan
    assertThat(driver.findElement(By.cssSelector(".jsfcrud_odd_row:nth-child(7) > td:nth-child(2)")).getText(), is("ayan"));
  }
}
