// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class CreateSliderPassSelenium {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createslider() {
    // Test name: create slider
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/Slider/ | 
    driver.get("http://localhost:8080/Slider/");
    // 2 | setWindowSize | 945x1060 | 
    driver.manage().window().setSize(new Dimension(945, 1060));
    // 3 | click | linkText=Show All Slider Items | 
    driver.findElement(By.linkText("Show All Slider Items")).click();
    // 4 | click | linkText=Create New Slider | 
    driver.findElement(By.linkText("Create New Slider")).click();
    // 5 | click | id=j_idt12:size | 
    driver.findElement(By.id("j_idt12:size")).click();
    // 6 | type | id=j_idt12:size | 40
    driver.findElement(By.id("j_idt12:size")).sendKeys("40");
    // 7 | click | id=j_idt12:x | 
    driver.findElement(By.id("j_idt12:x")).click();
    // 8 | type | id=j_idt12:x | 10
    driver.findElement(By.id("j_idt12:x")).sendKeys("10");
    // 9 | click | id=j_idt12:y | 
    driver.findElement(By.id("j_idt12:y")).click();
    // 10 | type | id=j_idt12:y | 10
    driver.findElement(By.id("j_idt12:y")).sendKeys("10");
    // 11 | click | id=j_idt12:maxTravel | 
    driver.findElement(By.id("j_idt12:maxTravel")).click();
    // 12 | type | id=j_idt12:maxTravel | 10
    driver.findElement(By.id("j_idt12:maxTravel")).sendKeys("10");
    // 13 | click | id=j_idt12:currentTravel | 
    driver.findElement(By.id("j_idt12:currentTravel")).click();
    // 14 | click | id=j_idt12:currentTravel | 
    driver.findElement(By.id("j_idt12:currentTravel")).click();
    // 15 | doubleClick | id=j_idt12:currentTravel | 
    {
      WebElement element = driver.findElement(By.id("j_idt12:currentTravel"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 16 | type | id=j_idt12:currentTravel | 10
    driver.findElement(By.id("j_idt12:currentTravel")).sendKeys("10");
    // 17 | click | id=j_idt12:mvtDirection | 
    driver.findElement(By.id("j_idt12:mvtDirection")).click();
    // 18 | type | id=j_idt12:mvtDirection | 1100
    driver.findElement(By.id("j_idt12:mvtDirection")).sendKeys("1100");
    // 19 | click | id=j_idt12:dirChangeCount | 
    driver.findElement(By.id("j_idt12:dirChangeCount")).click();
    // 20 | type | id=j_idt12:dirChangeCount | 010
    driver.findElement(By.id("j_idt12:dirChangeCount")).sendKeys("010");
    // 21 | click | linkText=Save | 
    driver.findElement(By.linkText("Save")).click();
    // 22 | assertText | css=table:nth-child(1) td | Slider was successfully created.
    // Slider was successfully created.
    assertThat(driver.findElement(By.cssSelector("table:nth-child(1) td")).getText(), is("Slider was successfully created."));
  }
}
