// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class LoginFailSelenium {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginFail() {
    // Test name: Login Fail
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/Slider/faces/slider/List.xhtml | 
    driver.get("http://localhost:8080/Slider/faces/slider/List.xhtml");
    // 2 | setWindowSize | 1294x1080 | 
    driver.manage().window().setSize(new Dimension(1294, 1080));
    // 3 | click | id=j_username | 
    driver.findElement(By.id("j_username")).click();
    // 4 | type | id=j_username | 1234
    driver.findElement(By.id("j_username")).sendKeys("1234");
    // 5 | click | id=j_password | 
    driver.findElement(By.id("j_password")).click();
    // 6 | type | id=j_password | 1234
    driver.findElement(By.id("j_password")).sendKeys("1234");
    // 7 | click | css=input:nth-child(1) | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 8 | click | id=j_username | 
    driver.findElement(By.id("j_username")).click();
    // 9 | type | id=j_username | Guntas_admin
    driver.findElement(By.id("j_username")).sendKeys("Guntas_admin");
    // 10 | click | id=j_password | 
    driver.findElement(By.id("j_password")).click();
    // 11 | type | id=j_password | 1234567890
    driver.findElement(By.id("j_password")).sendKeys("1234567890");
    // 12 | click | css=input:nth-child(1) | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 13 | click | id=j_username | 
    driver.findElement(By.id("j_username")).click();
    // 14 | type | id=j_username | Guntas_admin
    driver.findElement(By.id("j_username")).sendKeys("Guntas_admin");
    // 15 | type | id=j_username | Guntas_
    driver.findElement(By.id("j_username")).sendKeys("Guntas_");
    // 16 | click | id=j_password | 
    driver.findElement(By.id("j_password")).click();
    // 17 | type | id=j_password | 1234
    driver.findElement(By.id("j_password")).sendKeys("1234");
    // 18 | click | css=input:nth-child(1) | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 19 | click | id=j_username | 
    driver.findElement(By.id("j_username")).click();
    // 20 | type | id=j_username | Guntas_admin
    driver.findElement(By.id("j_username")).sendKeys("Guntas_admin");
    // 21 | click | id=j_password | 
    driver.findElement(By.id("j_password")).click();
    // 22 | type | id=j_password | 1234
    driver.findElement(By.id("j_password")).sendKeys("1234");
    // 23 | click | css=input:nth-child(1) | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 24 | assertText | linkText=Create New Slider | Create New Slider
    // Login only when correctly matching login and id are put at once
    assertThat(driver.findElement(By.linkText("Create New Slider")).getText(), is("Create New Slider"));
  }
}
