// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class LoginSuccessSelenium {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void loginsuccess() {
    // Test name: Login success
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/Slider/faces/slider/List.xhtml | 
    driver.get("http://localhost:8080/Slider/faces/slider/List.xhtml");
    // 2 | setWindowSize | 1294x1080 | 
    driver.manage().window().setSize(new Dimension(1294, 1080));
    // 3 | click | id=j_username | 
    driver.findElement(By.id("j_username")).click();
    // 4 | type | id=j_username | Guntas_admin
    driver.findElement(By.id("j_username")).sendKeys("Guntas_admin");
    // 5 | type | id=j_password | 1234
    driver.findElement(By.id("j_password")).sendKeys("1234");
    // 6 | click | css=input:nth-child(1) | 
    driver.findElement(By.cssSelector("input:nth-child(1)")).click();
    // 7 | assertText | linkText=Create New Slider | Create New Slider
    // successful login
    assertThat(driver.findElement(By.linkText("Create New Slider")).getText(), is("Create New Slider"));
  }
}
